on: [push]

jobs:
  wiremock-test:
    runs-on: ubuntu-latest
    name: Set up WireMock as a standalone process
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Action E2E Test
        uses: williamhaw/setup-wiremock-action@v0.1.2
        id: setup-wiremock
        with:
          mappings: ./src/test/java/
          files: './target/test-classes/__files/'
          command: 'node --version'
      - name: Get the WireMock standard output
        run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"
